### User Signin/Login
POST https://g-activity.gnusa.id/service/auth/mlogin HTTP/1.1
content-type: application/cbor
# uspw: {"user":"max@ipm.id","pass":"admin123"}
uspw: {"user":"admin@ipm.id","pass":"ipm123"}
# uspw: {"user":"alex@ipm.id","pass":"oxw6rdp8"}


### User Status (Logged in)
GET https://g-activity.gnusa.id/service/auth/status HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I
param: user

### User Signout/Logout
POST https://g-activity.gnusa.id/service/auth/logout HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Find Enum
# https://g-activity.gnusa.id/service/_enum/browse/:app/:module
GET https://g-activity.gnusa.id/service/_enum/browse/gactivity/workspaceType HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Find Member (Post)
# https://g-activity.gnusa.id/service/member/find
POST https://g-activity.gnusa.id/service/member/find HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{   
    // untuk pencarian member di halaman workspace
    "workspace_id":"7c89df23-b54a-4b80-acdc-6a5c9ef1da55", 

    // untuk pencarian member di halaman project
    //"project_id":"05618043-ae7f-425c-a7c9-530849f3534e", 

    // untuk pencarian member di halaman documentation
    //"document_id":"88ebd905-6a91-4c7f-9dd0-49cb97a5340c", 

    // untuk pencarian member di halaman mom
    //"mom_id":"7c89df23-b54a-4b80-acdc-6a5c9ef1da55", 

    "keyword":"john"
}