### User (Add)
# _active 1= Aktif | -1= Tidak Aktif
# r_id (ambil dari combo role)
POST https://g-activity.gnusa.id/service/baseuser HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "username":"alex@gmail.com",
    "fullname":"Alex",
    "email":"alex@gmail.com",
    "password":"123qwe",
    "r_id": "XXXX",
    "_active":1
}


### User (Edit)
# _active 1= Aktif | -1= Tidak Aktif
# r_id (ambil dari combo role)
PUT https://g-activity.gnusa.id/service/baseuser/c5a20c09-5b1f-4bb3-af72-84365a7c577c HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "username":"alex@gmail.com",
    "fullname":"Alex",
    "email":"alex@gmail.com",
    "password":"123qwe",
    "r_id": "XXXX",
    "_active":1
}

### User (GET)
GET http://g-activity.gnusa.id/service/baseuser HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I