### Documentation (Add)
POST https://s-gactivity.gnusa.id/gactivity-service/documentation HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw

{
    "workspace_id":"c5a20c09-5b1f-4bb3-af72-84365a7c577c",
    "project_id":"05618043-ae7f-425c-a7c9-530849f3534e",
    "privacy":-1
}


### Documentation (Edit)
# PUT https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID HTTP/1.1
PUT https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw

{
    "name":"iService",
    "description":"Document Project iService IBS",
    "privacy":-1
}


### Documentation (Delete)
# DELETE https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID HTTP/1.1
DELETE https://s-gactivity.gnusa.id/gactivity-service/documentation/50e029f6-3de9-454b-bfdf-0f6b1667f4a4 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation - My Document (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/05618043-ae7f-425c-a7c9-530849f3534e/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation - Shared (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/05618043-ae7f-425c-a7c9-530849f3534e/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation - Detail (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation Team (Add)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:projectID/:documentID/team
POST https://s-gactivity.gnusa.id/gactivity-service/documentation/14bcbd62-feb3-4870-86b4-247ff1a9e0ef/6f76ba63-d294-40bd-a998-4faf0a348d0b/team HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkYW5lLmdudXNhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.8jVOddgza5C6g-Y4oeP-HXAiZZs45ivNDxdiaQKSvQU

["82fa7b9a-4455-4503-af6d-c8d02f7bf5e0"]


### Documentation Team (Delete/Remove/Kick)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID/team/rm
DELETE  https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/team/rm HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw

["28e12a2a-894b-444b-af8e-65be3059f2cf"]


### Documentation Team - List (Get)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID/team/1
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/team/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation Team - Count (Get)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID/team/2
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/team/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation Page (Add)
# pid: isi dengan id dari parent page. kalau parent diisi "ortu"
# device: default diisi "1"
POST https://s-gactivity.gnusa.id/gactivity-service/documentation/page HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw

{
    "document_id":"88ebd905-6a91-4c7f-9dd0-49cb97a5340c",
    "device":1,
    "pid":"ortu"
}


### Documentation Page (Edit)
# lock: -1 (false) | 1 true
# subHeader: -1 (false) | 1 true
PUT https://s-gactivity.gnusa.id/gactivity-service/documentation/page/c0fa4fd2-d630-437c-9040-ce7ffede312a HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw

{
    "title":"Page 1",
    "lock":-1,
    "subHeader":-1,
    "device":1,
    "content":[{
        "id": 1,
        "index": 1,
        "type": "title",
        "text": "Sistem yang akan kita buat adalah sistem AI"
    },{
        "index": 2,
        "cols": [{
            "index": "2-1",
            "rows": [
            {
                "id": 3,
                "type": "tip",
                "image": "/tip.png",
                "title": "<p>Tips sistem AI</p>\n",
                "description": "Make writing stand out",
                "text": "<p>AI harus bisa kita bangun bersama-sama hal ini akan lebih bagus apabila kita&nbsp; samakan<br>penerapan pertama<br></p>\n",
                "index": "2-1-1"
            },
            {
                "id": 2,
                "description": "Just start writing with plain text",
                "type": "paragraph",
                "image": "/paragraph.png",
                "text": "<p>Paragraf pertama kita akan&nbsp; bisa memperbaiki sistem ini</p>\n",
                "index": "2-1-2"
            }
            ]
        },
        {
            "index": "2-2",
            "rows": []
        }]
    }]
}


### Documentation Page (Delete)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/page
DELETE  https://s-gactivity.gnusa.id/gactivity-service/documentation/page HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw

["c0fa4fd2-d630-437c-9040-ce7ffede312a"]


### Documentation Page - List (Get)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID/page/list
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/page/list HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTuiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation Page - Detail (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/page/d/c0fa4fd2-d630-437c-9040-ce7ffede312a HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5nbnVzYSIsInBhc3N3b3JkIjoiZTNiYjJhYTI5ODI1MWE0NDdjNmM1ODFhNGI5YzNiMjc1MzM2ZGU3NCJ9.FrmNowqb_hE5CZR-Cr0l7o7HbjGFdahk68QMW3Nu7zw


### Documentation Page (re-position)
PUT https://s-gactivity.gnusa.id/gactivity-service/documentation/_repospage HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

[
    {
        "id":"c0fa4fd2-d630-437c-9040-ce7ffede312a",
        "pos":1,
    }
]