### User Signin/Login
POST https://s-gactivity.gnusa.id/gactivity-service/auth/mlogin HTTP/1.1
content-type: application/cbor
# uspw: {"user":"max@ipm.id","pass":"admin123"}
uspw: {"user":"admin@ipm.id","pass":"ipm123"}


### User Signout/Logout
POST https://s-gactivity.gnusa.id/gactivity-service/auth/logout HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

### User Status (Logged in)
POST http://s-gactivity.gnusa.id/gactivity-service/auth/status HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I
param: user


### Find Enum
# https://s-gactivity.gnusa.id/gactivity-service/_enum/browse/:app/:module
GET https://s-gactivity.gnusa.id/gactivity-service/_enum/browse/gactivity/workspaceType HTTP/1.1
content-type: application/cbor
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

### Workspace Get
GET https://s-gactivity.gnusa.id/gactivity-service/workspace/e22cfbe9-65d9-4cb9-b655-c4d895dcf24e HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

### WorkSpace (Add)
# privacy : -1 (Private) | 1 (Public)
# type : ambil dari API find ENUM
POST https://s-gactivity.gnusa.id/gactivity-service/workspace HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "name":"Sushimoo",
    "website":"sushimoo.id",
    "type":"f0d32eab-50a3-46f0-aeec-4dd8e1439474",
    "privacy":-1,
    "description":"Sushimoo workspaces"
}


### WorkSpace (Edit)
# https://s-gactivity.gnusa.id/gactivity-service/workspace/:workspaceID
# privacy : -1 (Private) | 1 (Public)
# type : ambil dari API find ENUM
PUT https://s-gactivity.gnusa.id/gactivity-service/workspace/7c89df23-b54a-4b80-acdc-6a5c9ef1da55 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "name":"Sushimoo",
    "website":"sushimoo.id",
    "type":"f0d32eab-50a3-46f0-aeec-4dd8e1439474",
    "privacy":-1,
    "description":"Sushimoo workspaces 123456"
}


### WorkSpace (Delete)
DELETE https://s-gactivity.gnusa.id/gactivity-service/workspace/9c39c88d-bfe7-4337-8045-039a39805f37 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### WorkSpace - My workspace (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/workspace/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### WorkSpace - Shared (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/workspace/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### WorkSpace - Invited (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/workspace/3 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### WorkSpace Team (Add)
# https://s-gactivity.gnusa.id/gactivity-service/workspace/:workspaceID/team
POST https://s-gactivity.gnusa.id/gactivity-service/workspace/7c89df23-b54a-4b80-acdc-6a5c9ef1da55/team HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

["designer@ipm.id","max@ipm.id"]


### WorkSpace Team (Delete/Remove/Kick)
# https://s-gactivity.gnusa.id/gactivity-service/workspace/:workspaceID/team/rm
DELETE  https://s-gactivity.gnusa.id/gactivity-service/workspace/7c89df23-b54a-4b80-acdc-6a5c9ef1da55/team/rm HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

["946c54c5-0245-411a-a7b2-d53e006f7118"]


### WorkSpace Team - List (Get)
# invited & active member
# https://s-gactivity.gnusa.id/gactivity-service/workspace/:workspaceID/team/1
GET https://s-gactivity.gnusa.id/gactivity-service/workspace/7c89df23-b54a-4b80-acdc-6a5c9ef1da55/team/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### WorkSpace Team - Count (Get)
# Only active member on workspace
# https://s-gactivity.gnusa.id/gactivity-service/workspace/:workspaceID/team/2
GET https://s-gactivity.gnusa.id/gactivity-service/workspace/7c89df23-b54a-4b80-acdc-6a5c9ef1da55/team/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### WorkSpace Team - resend link invitation (Get)
# https://s-gactivity.gnusa.id/gactivity-service/workspace/:workspaceID/resend/:id
GET https://s-gactivity.gnusa.id/gactivity-service/workspace/7c89df23-b54a-4b80-acdc-6a5c9ef1da55/resend/b32059af-8e91-4a0f-a7f2-008590822f7f HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Find Member (Post)
# https://s-gactivity.gnusa.id/gactivity-service/member/find
POST https://s-gactivity.gnusa.id/gactivity-service/member/find HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "workspace_id":"e22cfbe9-65d9-4cb9-b655-c4d895dcf24e",
    //"project_id":"05618043-ae7f-425c-a7c9-530849f3534e",
    //"document_id":"88ebd905-6a91-4c7f-9dd0-49cb97a5340c",
    "keyword":""
}


### WorkSpace Team - Accept invitation (PUT)
# https://s-gactivity.gnusa.id/gactivity-service/workspace/:workspaceID/accept/:id
PUT https://s-gactivity.gnusa.id/gactivity-service/workspace/7c89df23-b54a-4b80-acdc-6a5c9ef1da55/accept/c67ac526-ca07-42e7-b46c-d6a4334618e7 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZ3Vlc3QxQGlwbS5pZCIsInBhc3N3b3JkIjoiOTE0YzBlMWEyZWJmOTYwOTk4NDRmNjhjOTZlMDFiMmVjNjlhNzM4MSJ9.bb1Dn7O6PMM_mou3hvtKmljZQKB6zd-tgZ7PlsT1VQY


### Project (Add)
# privacy : -1 (Private) | 1 (Public)
POST https://s-gactivity.gnusa.id/gactivity-service/project HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "name":"Android",
    "workspace_id":"c5a20c09-5b1f-4bb3-af72-84365a7c577c",
    "privacy":-1,
    "description":"Android Sushimoo", 
    "assigned": "AeDoh9uH,a9fc1a99-14b1-41f9-9009-6ebed0e046e4"
}


### Project (Edit)
# privacy : -1 (Private) | 1 (Public)
PUT https://s-gactivity.gnusa.id/gactivity-service/project/05618043-ae7f-425c-a7c9-530849f3534e HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "name":"Android",
    "privacy":-1,
    "description":"Project android sushimoo"
}


### Project (Delete)
DELETE https://s-gactivity.gnusa.id/gactivity-service/project/05618043-ae7f-425c-a7c9-530849f3534e HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Project - My Project (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/Project/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Project - Shared (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/project/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Project Team (Add)
# https://s-gactivity.gnusa.id/gactivity-service/project/:workspaceID/:projectID/team
POST https://s-gactivity.gnusa.id/gactivity-service/project/7c89df23-b54a-4b80-acdc-6a5c9ef1da55/05618043-ae7f-425c-a7c9-530849f3534e/team HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

["AeDoh9uH"]


### Project Team (Delete/Remove/Kick)
# https://s-gactivity.gnusa.id/gactivity-service/project/:projectID/team/rm
DELETE  https://s-gactivity.gnusa.id/gactivity-service/project/05618043-ae7f-425c-a7c9-530849f3534e/team/rm HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

["6e0fd4da-0e49-42c7-bdac-75cee238fbec"]


### Project Team - List (Get)
# https://s-gactivity.gnusa.id/gactivity-service/project/:projectID/team/1
GET https://s-gactivity.gnusa.id/gactivity-service/project/05618043-ae7f-425c-a7c9-530849f3534e/team/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Project Team - Count (Get)
# https://s-gactivity.gnusa.id/gactivity-service/project/:projectID/team/2
GET https://s-gactivity.gnusa.id/gactivity-service/project/05618043-ae7f-425c-a7c9-530849f3534e/team/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Documentation (Add)
POST https://s-gactivity.gnusa.id/gactivity-service/documentation HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "workspace_id":"c5a20c09-5b1f-4bb3-af72-84365a7c577c",
    "project_id":"05618043-ae7f-425c-a7c9-530849f3534e",
    "privacy":-1
}


### Documentation (Edit)
# PUT https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID HTTP/1.1
PUT https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

{
    "name":"iService",
    "description":"Project iService IBS",
    "privacy":-1
}


### Documentation (Delete)
# DELETE https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID HTTP/1.1
DELETE https://s-gactivity.gnusa.id/gactivity-service/documentation/50e029f6-3de9-454b-bfdf-0f6b1667f4a4 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Documentation - My Document (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/05618043-ae7f-425c-a7c9-530849f3534e/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Documentation - Shared (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/05618043-ae7f-425c-a7c9-530849f3534e/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Documentation Team (Add)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:projectID/:documentID/team
POST https://s-gactivity.gnusa.id/gactivity-service/documentation/05618043-ae7f-425c-a7c9-530849f3534e/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/team HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

["AeDoh9uH","a9fc1a99-14b1-41f9-9009-6ebed0e046e4"]


### Documentation Team (Delete/Remove/Kick)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID/team/rm
DELETE  https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/team/rm HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I

["28e12a2a-894b-444b-af8e-65be3059f2cf"]


### Documentation Team - List (Get)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID/team/1
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/team/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I


### Documentation Team - Count (Get)
# https://s-gactivity.gnusa.id/gactivity-service/documentation/:documentID/team/2
GET https://s-gactivity.gnusa.id/gactivity-service/documentation/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/team/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW5AaXBtLmlkIiwicGFzc3dvcmQiOiI5ODkzMzRjZjYzYjQ0YzE1NDJiYmU4NDRmMDk2ZjVmYTc4MjVhNTc0In0.UhuyYiicBaRzf_6_MSFTn64MgmNsdBDU_FMfvuxeA7I