### MoM (Add)
POST https://s-gactivity.gnusa.id/gactivity-service/mom HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

{
    "workspace_id":"c5a20c09-5b1f-4bb3-af72-84365a7c577c",
    "project_id":"05618043-ae7f-425c-a7c9-530849f3534e",
    "privacy":-1
}


### MoM (Edit)
# PUT https://s-gactivity.gnusa.id/gactivity-service/mom/:momId HTTP/1.1
# start_time : %Y-%m-%dT%H:%M:%S.%f%z
# end_time : %Y-%m-%dT%H:%M:%S.%f%z
PUT https://s-gactivity.gnusa.id/gactivity-service/mom/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

{
    "title":"iService",
    "place":"Document Project iService IBS",
    "address":"",
    "action_list":[{
        "checked":1,
        "value":"action 1"
    },{
        "checked":0,
        "value":"action 2"
    }],
    "agenda":[
        "Agenda 1",
        "Agenda 2",
        "Agenda 3"
    ],
    "mom_date":"2023-03-18 00:00:00",
    "start_time":"2023-03-18T09:00:00.000Z", 
    "end_time":"2023-03-18T11:00:00.000Z",
    "conclusion":"kesimpulan disini...",
    "privacy":-1
}


### MoM (Delete)
# DELETE https://s-gactivity.gnusa.id/gactivity-service/mom/:momId HTTP/1.1
DELETE https://s-gactivity.gnusa.id/gactivity-service/mom/50e029f6-3de9-454b-bfdf-0f6b1667f4a4 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM - My MoM (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/mom/05618043-ae7f-425c-a7c9-530849f3534e/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM - Shared (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/mom/05618043-ae7f-425c-a7c9-530849f3534e/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM - Detail (GET)
GET https://s-gactivity.gnusa.id/gactivity-service/mom/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM Team (Add)
# https://s-gactivity.gnusa.id/gactivity-service/mom/team/:projectID/:documentID
POST https://s-gactivity.gnusa.id/gactivity-service/mom/team/05618043-ae7f-425c-a7c9-530849f3534e/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

["AeDoh9uH","a9fc1a99-14b1-41f9-9009-6ebed0e046e4"]


### MoM Team (Delete/Remove/Kick)
# https://s-gactivity.gnusa.id/gactivity-service/mom/team/rm/:documentID
DELETE  https://s-gactivity.gnusa.id/gactivity-service/mom/team/rm/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

["28e12a2a-894b-444b-af8e-65be3059f2cf"]


### MoM Team - List (Get)
# https://s-gactivity.gnusa.id/gactivity-service/mom/team/:documentID/1
GET https://s-gactivity.gnusa.id/gactivity-service/mom/team/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/1 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM Team - Count (Get)
# https://s-gactivity.gnusa.id/gactivity-service/mom/team/:documentID/2
GET https://s-gactivity.gnusa.id/gactivity-service/mom/team/88ebd905-6a91-4c7f-9dd0-49cb97a5340c/2 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM Point (Add)
POST https://s-gactivity.gnusa.id/gactivity-service/mom/point HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

{
    "mom_id":"88ebd905-6a91-4c7f-9dd0-49cb97a5340c",
    "result":"Ini poin meeting",
    "target_date":"2023-03-18 00:00:00",
    "pic":"Bambang",
    "state_by":"Agus"
}


### MoM Point (Edit)
PUT https://s-gactivity.gnusa.id/gactivity-service/mom/point/c0fa4fd2-d630-437c-9040-ce7ffede312a HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

{
    "result":"Ini poin meeting",
    "target_date":"2023-03-18 00:00:00",
    "pic":"Bambang",
    "state_by":"Agus"
}


### MoM Point (Delete)
# https://s-gactivity.gnusa.id/gactivity-service/mom/point/:id
DELETE  https://s-gactivity.gnusa.id/gactivity-service/mom/point/c0fa4fd2-d630-437c-9040-ce7ffede312a HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM Point - List (Get)
# https://s-gactivity.gnusa.id/gactivity-service/mom/point/:momId
GET https://s-gactivity.gnusa.id/gactivity-service/mom/point/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM Participant (Add)
# https://s-gactivity.gnusa.id/gactivity-service/mom/participant
# note: kalau participant diambil dari member maka utk isian field email,name & uid diambil dari data member
POST https://s-gactivity.gnusa.id/gactivity-service/mom/participant HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

// kalau participant dari team member project
{
    "mom_id":"88ebd905-6a91-4c7f-9dd0-49cb97a5340c",
    "email":"alex@ipm.id",
    "name":"Alex",
    "position":"Manager",
    "company":"XL",
    "uid":"856fad33-7d37-4e89-8830-53d2361b259c"
}

// kalau participant bukan dari tam member project
# {
#     "mom_id":"88ebd905-6a91-4c7f-9dd0-49cb97a5340c",
#     "name":"Alex",
#     "position":"Manager",
#     "company":"XL"
# }


### MoM Participant (Edit)
# https://s-gactivity.gnusa.id/gactivity-service/mom/participant/:id
PUT https://s-gactivity.gnusa.id/gactivity-service/mom/participant/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs

{
    "position":"Manager",
    "company":"XL"
}

### MoM Participant (Delete)
# https://s-gactivity.gnusa.id/gactivity-service/mom/participant/:id
DELETE  https://s-gactivity.gnusa.id/gactivity-service/mom/participant/88ebd905-6a91-4c7f-9dd0-49cb97a5340c HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs


### MoM Participant - List (Get)
# https://s-gactivity.gnusa.id/gactivity-service/mom/participant/:momId
GET https://s-gactivity.gnusa.id/gactivity-service/mom/participant/7315ea99-90b7-4267-82d3-844508726000 HTTP/1.1
content-type: application/json
XA: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiemlkZGFuZmhkbHZ5MTJAZ21haWwuY29tIiwicGFzc3dvcmQiOiJlM2JiMmFhMjk4MjUxYTQ0N2M2YzU4MWE0YjljM2IyNzUzMzZkZTc0In0.CHyjACbHB5IaH21D29OsUfuoWFMz_dtqTvaFFqBWwCs